### ISSUE TITLE
TOC on GitHub Pages

### ISSUE THREAD

**Issue by vahid-dan** [toshimaru/jekyll-toc#29]
The plugin works fine locally, but when I push the website to the GitHub pages, it doesn't work there. Is there any way to make it work on GitHub beside producing a static version of the website in `gh-pages` branch and pushing that to the GitHub?

Thanks a lot. :-)

Cheers,
Vahid

**Comment by toshimaru** [comment]
You're right, you can NOT use jekyll-toc powered by official GitHub Pages gem because available plugins are limited. 

[Configuring Jekyll plugins - User Documentation](https://help.github.com/articles/configuring-jekyll-plugins/)

To use jekyll-toc plugin, build your site locally and push it onto the `gh-pages` branch. I deployed my personal blog site in that way. The source code is open, so you can see how it works. https://github.com/toshimaru/blog.toshimaru.net
